### ISSUE TITLE
Build error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [Joseph5610/fxradio#16]
**Describe the bug**
When I build the program from source,I got errors:
```
$ ./gradlew jfxNative

> Configure project :
Project : => no module-info.java found

> Task :jfxNative FAILED
        Using packager io.github.fvarrui.javapackager.packagers.LinuxPackager
        Creating app ...
            Initializing packager ...
                PackagerSettings [outputDirectory=$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native, licenseFile=null, iconFile=null, generateInstaller=true, forceInstaller=false, mainClass=online.hudacek.fxradio.FxRadioKt, name=FXRadio, displayName=FXRadio, version=0.16.0, description=Internet Radio Directory, url=https://hudacek.online/fxradio, administratorRequired=false, organizationName=FXRadio, organizationUrl=https://hudacek.online/fxradio, organizationEmail=fxradio@hudacek.online, bundleJre=true, customizedJre=false, jrePath=null, jdkPath=/usr/lib/jvm/java-20-openjdk, additionalResources=[], modules=[], additionalModules=[], platform=linux, envPath=null, vmArgs=[-Xms256m, -Xmx2048m, -XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC], runnableJar=null, copyDependencies=true, jreDirectoryName=jre, winConfig=null, linuxConfig=LinuxConfig [categories=[Utility], generateDeb=true, generateRpm=true, generateAppImage=true, pngFile=null, wrapJar=true], macConfig=null, createTarball=false, createZipball=true, extra={}, useResourcesAsWorkingDir=true, assetsDir=$HOME/.cache/paru/clone/fxradio-0.16.0/src/main/deploy/package, classpath=null, jreMinVersion=null, manifest=Manifest [additionalEntries={Implementation-Version=0.16.0}, sections=[]], additionalModulePaths=[], fileAssociations=null, packagingJdk=$HOME/.gradle/jdks/azul_systems__inc_-19-amd64-linux/zulu19.32.15-ca-fx-jdk19.0.2-linux_x64, scripts=Scripts [bootstrap=null, preInstall=null, postInstall=null], arch=x64]
            Packager initialized!
            
            Creating app structure ...
                Removing folder [$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio]
                Old app folder removed $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio
                App folder created: $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio
                Assets folder created: $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets
            App structure created!
            
            Resolving resources ...
                License file found: $HOME/.cache/paru/clone/fxradio-0.16.0/LICENSE
                Copying resource [/linux/default-icon.png] to file [$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets/FXRadio.png]
                Icon file resolved: $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets/FXRadio.png
                Effective additional resources [$HOME/.cache/paru/clone/fxradio-0.16.0/LICENSE, $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets/FXRadio.png]
            Resources resolved!
            
            Copying additional resources
                Copying file [$HOME/.cache/paru/clone/fxradio-0.16.0/LICENSE] to folder [$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio]
                Executing command: /bin/sh -c cd '$HOME/.gradle/daemon/8.1/.' && 'cp' $HOME/.cache/paru/clone/fxradio-0.16.0/LICENSE $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio/LICENSE
                Copying file [$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets/FXRadio.png] to folder [$HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio]
                Executing command: /bin/sh -c cd '$HOME/.gradle/daemon/8.1/.' && 'cp' $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/assets/FXRadio.png $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio/FXRadio.png
            All additional resources copied!
            
            Copying all dependencies ...
            Dependencies copied to $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio/libs!
            
            Creating runnable JAR...
            Runnable jar created in $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio-0.16.0-runnable.jar!
            
            Bundling JRE ... with $HOME/.gradle/jdks/azul_systems__inc_-19-amd64-linux/zulu19.32.15-ca-fx-jdk19.0.2-linux_x64
                Creating customized JRE ...
                Getting required modules ... 
                    It was not possible to determine the necessary modules. All modules will be included
                Required modules found: [ALL-MODULE-PATH]
                
                Creating JRE with next modules included: ALL-MODULE-PATH
                Using /usr/lib/jvm/java-20-openjdk/jmods modules directory
                Executing command: /bin/sh -c cd '$HOME/.gradle/daemon/8.1/.' && '$HOME/.gradle/jdks/azul_systems__inc_-19-amd64-linux/zulu19.32.15-ca-fx-jdk19.0.2-linux_x64/bin/jlink' --module-path /usr/lib/jvm/java-20-openjdk/jmods --add-modules ALL-MODULE-PATH --output $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio/jre --no-header-files --no-man-pages --strip-debug --compress=2
                错误: Error reading module: /usr/lib/jvm/java-20-openjdk/jmods/java.base.jmod
                java.lang.module.FindException: Error reading module: /usr/lib/jvm/java-20-openjdk/jmods/java.base.jmod
                        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:350)
                        at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:284)
                        at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:232)
                        at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
                        at java.base/jdk.internal.module.ModulePath.find(ModulePath.java:154)
                        at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.newModuleFinder(JlinkTask.java:468)
                        at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.initJlinkConfig(JlinkTask.java:387)
                        at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:271)
                        at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
                        at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)
                Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 64.0
                        at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1212)
                        at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:193)
                        at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:129)
                        at java.base/jdk.internal.module.ModulePath.readJMod(ModulePath.java:395)
                        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:343)
                        ... 9 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfxNative'.
> org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: $HOME/.gradle/jdks/azul_systems__inc_-19-amd64-linux/zulu19.32.15-ca-fx-jdk19.0.2-linux_x64/bin/jlink --module-path /usr/lib/jvm/java-20-openjdk/jmods [Ljava.lang.String;@6cd602ca --add-modules ALL-MODULE-PATH --output $HOME/.cache/paru/clone/fxradio-0.16.0/build/jfx/native/FXRadio/jre --no-header-files --no-man-pages --strip-debug --compress=2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 1 executed, 5 up-to-date
```

**Desktop (please complete the following information):**

- OS: EndeavourOS x86_64 6.1.33-1-lts
- openjdk version "20.0.1" 2023-04-18
- OpenJDK Runtime Environment (build 20.0.1+9)
- OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
- java-openjfx 20.0.1.u1-1

**Comment by zxp19821005** [comment]
I think maybe you can change it:
https://github.com/Joseph5610/fxradio/blob/master/README.md#:~:text=App%20requires%20JDK%2020%20and%20JavaFX%2020%20to%20build%20and%20run.

**Comment by zxp19821005** [comment]
BTW,will you please release a Linux distribution such as rpm or deb in the next time?

**Comment by Joseph5610** [comment]
> I think maybe you can change it: https://github.com/Joseph5610/fxradio/blob/master/README.md#:~:text=App%20requires%20JDK%2020%20and%20JavaFX%2020%20to%20build%20and%20run.

Hello, since then, the app already runs on JDK 20. Currently in the development branch, the app runs on JDK20 + JavaFX 21. 



> BTW,will you please release a Linux distribution package such as rpm or deb in the next release?

I don't plan to do this since I have no way to test it. Feel free to submit PR if you can.
